import { Geist, Geist_Mono, Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const inter = Inter({ subsets: ['latin'] });
const robotoMono = Roboto_Mono({
  weight:"400",
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto-mono', // Use 'variable' for easier multi-font management
});


export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`scroll-smooth ${inter.className} ${robotoMono.variable} `}>
      <body>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  )
}

